config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins
  get 'welcome/index'

   root 'welcome#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :photo,presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_params_devise, if: :devise_controller?

  protected

  def configure_params_devise
  	devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:name,:email,:password,:password_confirmation)}
  	
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description,:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <%= render "shared/navbar" %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name,"Nombre"  %><br>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>  
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :photo,"Foto" %><br>
      <%= f.text_field :photo, :class => 'form-control' %>
    </div>  
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :description;"Descripción" %><br>
      <%= f.text_field :description,:class =>'form-control' %>
    </div>   
  </div>
 
  <div class="actions">
    <% if accion = nil%> 
        <%accion="Crear" %>
     <% end -%>   
    <%= f.submit accion,:class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<div class="col-md-6">
		<h1>Editar Pin</h1>
	
		<%= render 'form' %>

		<%= link_to 'Ver', @pin %> |
		<%= link_to 'Atrás', pins_path %>
	</div>
</div>		

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Lista de Pins </h1>

<% @pins.each do |pin| %>
    
  <div class="col-md-3">
    <div class="thumbnail">  
      <%= pin.name %>
      <%= image_tag(pin.photo,:class => 'img-responsive') %>
      <%= pin.description %> <br>
      <div class="buttons" style="margin-top: 10px;margin-bottom: 10px;">
        <%= link_to 'Ver', pin ,:class => 'btn btn-primary'%>
        <% if user_signed_in? %>
          <%= link_to 'Editar', edit_pin_path(pin),:class => 'btn btn-primary' %>
          <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-primary' %>   
        <% end %>
           
      </div>
     
    </div>
   </div>   

<% end %><br>

<% if user_signed_in? %>
  <%= link_to 'Nuevo Pin', new_pin_path %>  
<% end %>

app/views/pins/new.html.erb
<div class="container">
	<div class="col-md-6">
		<h1>Agregar Pin</h1>

		<%= render 'form' %>

		<%= link_to 'Atrás', pins_path %>	
	</div>
		
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Name: </strong>
	<%= @pin.name %>
</p>

<p>
  <%= image_tag(@pin.photo) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Editar', edit_pin_path(@pin) %> |
<%= link_to 'Atrás', pins_path %>
<a href="" style="color:white;font-size: 2em;">
	<span class="glyphicon glyphicon-heart"></span>
</a>

app/views/shared/_navbar.html.erb
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Pincs</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= pins_path %>">Pins</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if current_user.nil? %>
          <li>
            <a href="<%= new_user_session_path %>">Entrar</a></li>
          <li >
            <a href="<%= new_user_registration_path %>">
            Registrarse
            </a>
          </li>
        <%else %>  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Perfil</a></li>
              <li><a href="#">Mis Post</a></li>
              <li><a href="#">Biografía</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="<%= destroy_user_session_path %>" data-method="delete">Cerrar Sesión</a></li>
            </ul>
          </li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="container">
	

	<h1>Titulo</h1>

	<p>Find me in app/views/welcome/index.html.erb</p>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi, libero tempore fugiat ratione velit reprehenderit dicta quam odit consequuntur unde dolor. Reprehenderit pariatur ut quis ipsam, unde soluta, explicabo odio.</p>
	<img src="https://liberadalinux.files.wordpress.com/2013/11/720px-arduino_logo-svg.png" alt="Logo de arduino"><br>
	<hr>
	<div class="row">
		<div class="col-md-4">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex quos, numquam cumque illum at quis. Ipsa maxime nihil perferendis labore, debitis sit magni a, error quas blanditiis, cum, minus adipisci.</p>
		</div>
	
		<div class="col-md-4">	
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur sapiente odio itaque dicta dolor provident, ipsa praesentium? Perspiciatis optio nisi laboriosam ipsam explicabo et tenetur. Eaque officiis atque corrupti, itaque!
			<a href="#" class="btn btn-info">Read More
			<span class="glyphicon glyphicon-plus-sign"></span>
			</a>
			
			</p>
		</div>
		<div class="col-md-4">	
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur sapiente odio itaque dicta dolor provident, ipsa praesentium? Perspiciatis optio nisi laboriosam ipsam explicabo et tenetur. Eaque officiis atque corrupti, itaque!
			<button class="btn btn-info"><span class="glyphicon glyphicon-plus-sign" style="color:redetge"></span></button>
			</p>
		</div>
	</div>	
</div>	